# Test
language: c
compiler:
  - gcc
#  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq gnucash
  - sudo apt-get install -qq swig xsltproc libdbd-sqlite3
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
script: ./autogen.sh && ./configure && make && make check
